#a: Test case ตามข้อ 1 
#1.เพิ่มพรรคการเมือง 3 พรรค
POST http://127.0.0.1:8000/Parties/

{
  "party_name": "พรรคประชาชน",
  "party_leader": "ณัฐพงษ์ เรืองปัญญาวุฒิ",
  "party_logo_url": "logo_ppp.jpg"
}
###
POST http://127.0.0.1:8000/Parties/

{
  "party_name": "พรรคเพื่อไทย",
  "party_leader": "ยศชนันดิ์ วงศวัสดิ์",
  "party_logo_url": "logo_pt.jpg"
}
###
POST http://127.0.0.1:8000/Parties/

{
  "party_name": "พรรคภูมิใจไทย",
  "party_leader": "อนุทิน ชาญวีรกูล",
  "party_logo_url": "logo_bjt.jpg"
}

###2.ดูรายชื่อพรรคการเมือง
GET http://127.0.0.1:8000/Parties/

###3. เพิ่มผู้สมัคร เขต 1 (3 คน จาก 3 พรรค)
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 1,
  "party_id": 1,
  "candidate_number": 1,
  "full_name": "นางสาวน้ำฟ้า เขตหนึ่ง"
}
###
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 1,
  "party_id": 2,
  "candidate_number": 2,
  "full_name": "นายยีน เขตหนึ่ง"
}
###
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 1,
  "party_id": 3,
  "candidate_number": 3,
  "full_name": "นางสาวโมจิ เขตหนึ่ง"
}

###4.เพิ่มผู้สมัคร เขต 2
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 2,
  "party_id": 1,
  "candidate_number": 1,
  "full_name": "นางสาวชมรี่ เขตสอง"
}
###
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 2,
  "party_id": 2,
  "candidate_number": 2,
  "full_name": "นางสาวอันอัน เขตสอง"
}
###
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 2,
  "party_id": 3,
  "candidate_number": 3,
  "full_name": "นายโอชิ เขตสอง"
}

###4.เพิ่มผู้สมัคร เขต 3
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 3,
  "party_id": 1,
  "candidate_number": 1,
  "full_name": "นายมาย เขตสาม"
}
###
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 3,
  "party_id": 2,
  "candidate_number": 2,
  "full_name": "นางสาวแพรวา เขตสาม"
}
###
POST http://127.0.0.1:8000/Candidates/

{
  "const_id": 3,
  "party_id": 3,
  "candidate_number": 3,
  "full_name": "นางสาวปราง เขตสาม"
}
###ดูรายชื่อผู้สมัคร (พร้อมรายละเอียดเขต)
GET http://127.0.0.1:8000/Candidates/


#b:Test case ตามข้อ 2 (อย่างน้อย 20 รายชื่อ)
###เพิ่มผู้มีสิทธิ์เลือกตั้ง
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000001",
  "full_name": "สมชาย ใจดี",
  "const_id": 1
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000002",
  "full_name": "สมหญิง รักชาติ",
  "const_id": 2
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000003",
  "full_name": "สมศักดิ์ มักจะมา",
  "const_id": 3
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000004",
  "full_name": "สมหมาย ทองมี",
  "const_id": 1
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000005",
  "full_name": "บุญช่วย คำดี",
  "const_id": 2
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000006",
  "full_name": "ประหยัด รักบ้าน",
  "const_id": 3
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000007",
  "full_name": "สายหยุด มูลแก้ว",
  "const_id": 1
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000008",
  "full_name": "ทองใบ แก้วคำ",
  "const_id": 2
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000009",
  "full_name": "ละมัย ใจบุญ",
  "const_id": 3
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000010",
  "full_name": "มนัส แสนสุข",
  "const_id": 1
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000011",
  "full_name": "วันเพ็ญ บุญมา",
  "const_id": 2
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000012",
  "full_name": "ไพโรจน์ ดวงดี",
  "const_id": 3
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000013",
  "full_name": "สำรวย คำปัน",
  "const_id": 1
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000014",
  "full_name": "ประยูร ทองสุข",
  "const_id": 2
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000015",
  "full_name": "แสงเดือน ใจงาม",
  "const_id": 3
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000016",
  "full_name": "ถวิล พรมมา",
  "const_id": 1
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000017",
  "full_name": "จำเนียร อินทร์ดี",
  "const_id": 2
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000018",
  "full_name": "มนัส แสนสุข",
  "const_id": 3
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000019",
  "full_name": "บุญส่ง รอดภัย",
  "const_id": 1
}
###
POST http://127.0.0.1:8000/Voters/

{
  "citizen_id": "0000000000020",
  "full_name": "มาลี สีทอง",
  "const_id": 2
}

###อัพเดทสถานะการลงคะแนนทีละคน
PATCH http://127.0.0.1:8000/Voters/20/vote_status

###ดูรายชื่อผู้มีสิทธิ์ทีละคน
GET http://127.0.0.1:8000/Voters/1

###ดูรายชื่อผู้มีสิทธิ์ทั้งหมด
GET http://127.0.0.1:8000/Voters/

#c:Test case ตามข้อ 3 
###แบบแบ่งเขต
POST http://127.0.0.1:8000/Ballots

{
  "const_id": 3,
  "candidate_id": 1,
  "party_id": null,
  "vote_type": "Constituency"
}

###แบบบัญชีรายชื่อ
POST http://127.0.0.1:8000/Ballots/

{
  "const_id": 2,
  "candidate_id": null,
  "party_id": 1,
  "vote_type": "PartyList"
}

###แสดงจำนวนผู้ลงคะแนนแยกตามเขตเลือกตั้ง
GET http://127.0.0.1:8000/Ballots/count

#d:Test case ตามข้อ 4 (แสดงผลการเลือกตั้ง)
###แสดงผลการเลือกตั้งแบบพรรคการเมือง (ภาพรวม)
GET http://127.0.0.1:8000/Results/Parties/

###แสดงผลการเลือกตั้งแบบพรรคการเมือง (เฉพาะเขต 1)
GET http://127.0.0.1:8000/Results/Parties/?const_id=1

###แสดงผลการเลือกตั้งแบบพรรคการเมือง (เฉพาะเขต 2)
GET http://127.0.0.1:8000/Results/Parties/?const_id=2

###แสดงผลการเลือกตั้งแบบพรรคการเมือง (เฉพาะเขต 3)
GET http://127.0.0.1:8000/Results/Parties/?const_id=3

###แสดงผลการเลือกตั้งแบบ ส.ส. เขต (ภาพรวม)
GET http://127.0.0.1:8000/Results/Candidates/

###แสดงผลการเลือกตั้งแบบ ส.ส. เขต (เฉพาะเขต 1)
GET http://127.0.0.1:8000/Results/Candidates/?const_id=1

###แสดงผลการเลือกตั้งแบบ ส.ส. เขต (เฉพาะเขต 2)
GET http://127.0.0.1:8000/Results/Candidates/?const_id=2

###แสดงผลการเลือกตั้งแบบ ส.ส. เขต (เฉพาะเขต 3)
GET http://127.0.0.1:8000/Results/Candidates/?const_id=3